server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: fastapi
    static_configs:
      - targets:
          - localhost
        labels:
          job: fastapi-app
          __path__: /var/log/fastapi/*.log
    pipeline_stages:
      - docker: {}
      - match:
          selector: '{job="fastapi-app"}'
          stages:
            - regex:
                expression: '^(?P<time>\S+) \[(?P<level>\w+)\] (?P<message>.*)'
            - labels:
                level:
            - output:
                source: message
